apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-gateway-ingress
spec:
  rules:
    - host: http://my-routine.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-gateway-service
                port:
                  number: 80