version: '3.8'

services:
  my-storage-db:
    image: postgres:latest
    container_name: my-storage-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-storage
    volumes:
      - my-storage-data:/var/lib/postgresql/data

volumes:
  my-storage-data: