version: '3.8'

services:
  my-storage-db:
    image: postgres:latest
    container_name: my-storage-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-storage
    volumes:
      - my-storage-data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  my-storage-data:
  mongodb_data: