version: '3.8'

services:
  my-storage-db:
    image: postgres:latest
    container_name: my-storage-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my-storage
    volumes:
      - my-storage-data:/var/lib/postgresql/data
    networks:
      - my-network
  mongodb:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my-network
  my-gateway-service:
    image: ghcr.io/narvane/my-gateway/my-gateway-image:v0.0.3
    container_name: my-gateway-service
    restart: always
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - my-network
  my-storage-service:
    image: ghcr.io/narvane/my-storage/my-storage-image:v0.2.7
    container_name: my-storage-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - my-network
volumes:
  my-storage-data:
  mongodb_data:
networks:
  my-network:
    driver: bridge